spring: 
  application: 
    name: coordination
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:musinsa
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

logging.level:
  org.hibernate.SQL: DEBUG
  org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
  org.springframework.sql: DEBUG